[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "spodnet"
version = "0.0.1"
description = "SpodNet package"


[tool.setuptools]
packages = ["spodnet"]
